
DELETE FROM MBDP_B_STEPDEF T WHERE T.APP='CBMS' AND T.CYCLE='D' AND T.DATA_SOURCE='CB01' AND T.STEPNO='CB01_D_CHK_0000';
insert into mbdp_b_stepdef (APP, CYCLE, DATA_SOURCE, PROG_TYPE, STEPNO, PROG, PROG_NAME, PARAMETER, DEFDATE, WEIGHT, ENABLE_FLAG)
values('CBMS', 'D', 'CB01', 'CHK', 'CB01_D_CHK_0000', 'PCKG_CBMS_INITC_CAIJH.PROC_CB01_VERCHG', 'CB01新程序跑旧批量', 'IN_PAR1=PROC|IN_PAR2=$WORKDATE|IN_PAR3=2016-05-24', TO_CHAR(SYSDATE,'YYYY-MM-DD'), 0,'1');
