CREATE DATABASE  IF NOT EXISTS `trading`;
USE `trading`;
DROP TABLE IF EXISTS PLAYER_TRADE_SKU_BINDING;
create table PLAYER_TRADE_SKU_BINDING( 
   TRADE_ID  BIGINT(15) unsigned NOT NULL COMMENT '交易编号',
   PLAYER_ID BIGINT(15) unsigned NOT NULL COMMENT '用户编号',
   SHOP_ID BIGINT(15) unsigned NOT NULL COMMENT '商店编号',
   SKU_ID BIGINT(15) unsigned NOT NULL COMMENT '货物编号',
   SHOP_SKU_AMOUNT BIGINT(15) unsigned COMMENT '货物数量',
   TRADE_TIME TIMESTAMP (6)  COMMENT '交易时间',
   primary Key (TRADE_ID) 
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='用户订单信息表';

   
