CREATE DATABASE IF NOT EXISTS `trading`;
USE `trading`;
DROP TABLE IF EXISTS PLAYER_TRADE_SKU_BINDING;
create table PLAYER_TRADE_SKU_BINDING( 
   TRADE_ID  BIGINT(15) unsigned NOT NULL COMMENT '交易编号',
   PLAYER_ID BIGINT(15) unsigned NOT NULL COMMENT '用户编号',
   SHOP_ID BIGINT(15)unsigned NOT NULL COMMENT  '商店编号',
   SKU_ID BIGINT(15) unsigned NOT NULL COMMENT '货物编号',
   SHOP_SKU_AMOUNT BIGINT(15) COMMENT '货物数量',
   primary Key (TRADE_ID) 
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='用户购物车信息表';

   
