CREATE DATABASE  IF NOT EXISTS `trading`;
USE `trading`;
DROP TABLE IF EXISTS SHOP_SKU_PRICE_BINDING;
create table SHOP_SKU_PRICE_BINDING( 
   SN_ID  bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '记录序号',
   SHOP_ID BIGINT(15) unsigned NOT NULL COMMENT '商店编号',
   SKU_ID BIGINT(15) unsigned NOT NULL COMMENT '货物编号',
   SKU_CURRENCY_TYPE BIGINT(15)  COMMENT '货币类型',
   SKU_CURRENCY_VALUE BIGINT(15) COMMENT '货币数值',
   primary Key (SN_ID),
   unique INDX_SKU_PRICE_BINDING1 (SHOP_ID,SKU_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='商店货物价目表';

   
