CREATE DATABASE  IF NOT EXISTS `trading`;
USE `trading`;
DROP TABLE IF EXISTS SKU_CURRENCY;
create table SKU_CURRENCY( 
   SKU_CURRENCY_TYPE BIGINT(15) unsigned NOT NULL COMMENT '货币类型',
   SKU_CURRENCY_NAME VARCHAR(60) NOT NULL COMMENT '货币名称',
   primary Key (SKU_CURRENCY_TYPE)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='货币字典表';

   
